name: test
version: 0.1
description: test
author: nathan
main: com.nathan.test.School_plugin


commands:
   Server_Time:
      description: This will give you the time.
      usage: /<command> [now]
   AddTime:
      permission: School_plugin.Addtime
      permission-message: You are not a teacher
      description: This is a demo command.
      usage: /<command> [time]


permissions:
    School_Plugin.Addtime:
        default: op