name: School_plugin
version: 1.0
description: test
author: nathan
main: com.nathan.test.School_plugin


commands:
   clear_times:
      description: This command clears the times set
      permission: School_plugin.clear_times
      permission-message: You are not a teacher
      usage: /<command>
   Server_Time:
      description: This will give you the time.
      usage: /<command> [now]
   AddTime:
      permission: School_plugin.Addtime
      permission-message: You are not a teacher
      description: This is a demo command.
      usage: /<command> [hour1|hour2|min1|min2]


permissions:
    School_Plugin.Addtime:
        default: op
    School_Plugin.clear_times:
        default: op